language: python
install:
    - sudo add-apt-repository -y ppa:chris-lea/protobuf
    - sudo apt-get update -qq
    - sudo apt-get install -qq libprotobuf-dev protobuf-compiler
    - pip install -r requirements.txt
script:
    - nosetests
